### ISSUE TITLE
Split DNS

### ISSUE THREAD

**Issue by rwaltr** [rwaltr/home-ops#627]
# Details

**Describe the solution you'd like:**

Need to figure out how to make external-dns and k8s_gateway work well

**Anything else you would like to add:**

@bjw-s and @onedr0p use kyverno to do some fun shenanigans for populating external-dns entires

**Additional Information:**

Maybe switch to nginx-ingress as well if I decide its worth it..

**Comment by rwaltr** [comment]
Fixed the external-dns public local ips problem,

Now to craft the dns pipeline

**Comment by onedr0p** [comment]
Coredns on your router pointing local domains to k8s gateway in your cluster is :chefs_kiss:

**Comment by rwaltr** [comment]
> Coredns on your router pointing local domains to k8s gateway in your cluster is :chefs_kiss:

I wish by my edgeos device is tiny, and I worry about putting non-official software on the edgeos-x because it's tiny.

Maybe hosted DNS in the cluster might work.

**Comment by onedr0p** [comment]
> Maybe hosted DNS in the cluster might work.

I used to do that but it didn't pass the waf when my cluster was having issues 😂
